### PR TITLE
Add wireguard support

### PR DESCRIPTION
**Pull request by kkoshelev**
This enables WireGuard kernel module and user level module.

The interface comes up and it is fully operational.

Note: some fixes are still needed for wg-quick shell script to accommodate some incompatibility of tools shipped with this kernel.

Tested:
# wg-quick up ./wg1.conf
[#] ip link add wg1 type wireguard
[#] wg setconf wg1 /dev/fd/63
[#] ip -4 address add 10.17.10.12/24 dev wg1
[#] ip link set mtu 1420 up dev wg1
~ # ip r
default via 10.1.10.1 dev wlan0 
10.1.10.0/24 dev wlan0 scope link  src 10.1.10.241 
10.1.10.1 dev wlan0 scope link 
10.17.10.0/24 dev wg1 scope link  src 10.17.10.12 
~ # ping 10.17.10.1
PING 10.17.10.1 (10.17.10.1): 56 data bytes
64 bytes from 10.17.10.1: seq=0 ttl=64 time=350.020 ms
64 bytes from 10.17.10.1: seq=1 ttl=64 time=172.680 ms

iperf3 tests show relatively decent performance over the tunnel given the circumstances. Over WiFi, it maintains 30Mbps with 5-10% of CPU load on RG351V.

### CODE REVIEW

**Comment by dhwz** [comment]
we've to check that internally first
do you agree to not to use wg-quick as this is getting the package out of sync with CoreELEC

**Comment by kkoshelev** [comment]
> do you agree to not to use wg-quick as this is getting the package out of sync with CoreELEC
Unfortunately, I do have a problem with that, because it severely limits WireGuard usability.

Typically, a consumer gets a WG config from their provider is a standard format, see link or QR code. And it imports it as is into the client. Done.
https://github.com/pirate/wireguard-docs#config-reference

CoreELEC decided to use WG as a ConnMan VPN plugin and came up with they own (inferior) configuration format for it.
https://wiki.libreelec.tv/configuration/wireguard 

As a result, one needs SSH access and somewhat knowledge about WG to craft that config from a standard one everyone else is using. Also config doesn't seem to support multiple peers and Pre/Post commands everyone else is using as well.

What we could potentially do is - create a folder on a SD card (WireGuard), and if consumer drops a .conf file (from VPN Provider like PIA, etc), the device will automatically establish the tunnel. In emustation, you can turn on/off it, similarly how you turn on/off wifi.

I don't know how ConnMan works exactly in terms of user story, but crafting config is a special format seems like a lot of work.

**Comment by pkegg** [comment]
**Summary**: 
- We would entertain updating to the latest versions of wireguard from corelec or libreelec and though we would prefer not to include `wg-quick` (as it's not included upstream), we can likely figure out some way to accommodate.  If this is still interesting to you - you're help in validating here would be appreciated - I'm interested in light VPN use cases as well.
- Changes beyond that are not likely to be accepted at least in the near term. 
  - I know that is frustrating, but VPN is not our core use case and deviating significantly from the upstream has long term support implications.
  - As an advanced user, with the above changes plus: custom_start.sh, start/stop scripts and/or custom systemd services you can likely achieve what you want on your device.  Other users can still follow coreelec/librelec guides and they will likely work.
 
**Details**
A few comments:
> CoreELEC decided to use WG as a ConnMan VPN plugin and came up with their own (inferior) configuration format for it.
> <https://wiki.libreelec.tv/configuration/wireguard>

So - I agree with this format being inferior and a pain.  That said - as soon as we materially deviate from our upstream - things get a lot harder.  For example:
- We no longer can easily pull in changes from upstream for these packages.  At a minimum it's more error prone.
- If we keep in sync with what is upstream, we can basically say "we believe that upstream docs will work" and it's only "best effort" support.  Once we make our own features - it's on us to support.  That's a much bigger ask.  If you cannot tell - we've been burned by some changes like this in the past and we do not add new functionality lightly :smiley: 
- Additionally, if we keep VPN packages, we should really should do the same approach for wireguard and openvpn.  Openvpn also uses the connman approach too, so we should consider how that would work too.

So - all that to say:
- We would definitely consider updating our wireguard and openvpn to the latest coreelec and/or libreelec versions if that is helpful .
  - As wg-quick is needed - we could discuss how to make it obvious that line is not from upstream with a comment or something.  If the team hated deviating the package from upstream at all - we could maybe provide a downloadable package with wq-quick installed under /storage or somewhere writable.
- Realistically - that is about the limit of what we would entertain for VPN changes in the near term.  Adding a VPN flag to the UI or making a lot of additions to how the packages automatically work (additional service + conf.d directory, a bunch of other changes around wireguard config, etc) is likely not going to happen due to the reasons above.
  - That said - you probably could make most of that happen for your own device via custom_start.sh, a user based systemd service and/or a script run under the ports directory (connect vpn, disconnect vpn, etc)
  - If more people started doing VPN connections and used your steps to configure the VPN via SSH and/or scripts - is it possible we would do more?  Yes - it's possible - but I don't want to promise anything. We try and be very careful when deviating from upstream.  I know that is potentially frustrating, but saying 'yes' to features is something very difficult to walk back.

**Comment by kkoshelev** [comment]
Some updates. In order to make wg-quick script to work the following needs to happen. This is not exhaustive list yet. 
1. "stat" needs to support "-c" command
2. "ip route" needs arbitrary tables support
3. "ip rule" needs support "not" subcommand

Those commands are not separate binaries as it is on "real" linux system, but part of single busybox binary which implements subset of those commands. I have a patches which would make (1), (3) work and still working on (2).
(1) is a CONFIG_FEATURE_STAT_FORMAT feature. 
(2) is CONFIG_FEATURE_IP_ROUTE_DIR change and some code changes
(3) is code patch to networking/iprule.c

**Pull request closed without merging**
